extends RefCounted

func run(context) -> void:
	await context.resetMain()
	await context.waitFrames(1)
	var board := context.CircuitBoard as Node2D
	var data := context.TestData as Dictionary
	var source := Vector2i(-12, -7)
	var sourceOther := source + Vector2i(2, 0)
	assert(board.call("placeTile", source, "or"))
	assert(board.call("placeTile", sourceOther, "xor"))
	assert(board.call("setTileState", sourceOther, false))
	board.call("setSelection", Rect2i(source, Vector2i(3, 1)))
	var sourceSelection: Dictionary = board.call("getSelectionItem")
	var moveStartInSelection := source + Vector2i(1, 0)
	assert(not (board.get("TileValues") as Dictionary).has(moveStartInSelection))
	assert((sourceSelection.get("bounds", Rect2i()) as Rect2i).has_point(moveStartInSelection))
	assert(board.call("canStartMoveAt", moveStartInSelection))
	var collisionOffset := Vector2i(0, 2)
	var collisionCoordinates := source + collisionOffset
	assert(board.call("placeTile", collisionCoordinates, "nor"))
	assert(board.call("beginMove", moveStartInSelection))
	board.call("updateMovePreview", moveStartInSelection + collisionOffset)
	assert(not bool(board.get("MovePreviewValid")))
	board.call("finishMove")
	var tileData: Dictionary = board.get("TileValues")
	assert(tileData.has(source))
	assert(tileData.has(collisionCoordinates))

	var moveOffset := Vector2i(4, 2)
	var movedPrimary := source + moveOffset
	var movedOther := movedPrimary + Vector2i(2, 0)
	var historyBeforeMove := (board.get("UndoStack") as Array).size()
	assert(board.call("beginMove", moveStartInSelection))
	board.call("updateMovePreview", moveStartInSelection + moveOffset)
	assert(bool(board.get("MovePreviewValid")))
	board.call("finishMove")
	assert(not tileData.has(source))
	assert(not tileData.has(sourceOther))
	assert(tileData.has(movedPrimary))
	assert(tileData.has(movedOther))
	assert(not bool(board.call("getTileState", movedOther)))
	assert((board.get("UndoStack") as Array).size() == historyBeforeMove + 1)
	context.sendCtrlShortcut(board, KEY_Z)
	assert(tileData.has(source))
	assert(tileData.has(sourceOther))
	assert(not bool(board.call("getTileState", sourceOther)))
	context.sendCtrlShortcut(board, KEY_U)
	assert(tileData.has(movedPrimary))
	assert(tileData.has(movedOther))
	assert(not bool(board.call("getTileState", movedOther)))
	data["movedPrimary"] = movedPrimary
	data["movedOther"] = movedOther
	context.sendCtrlShortcut(board, KEY_Z)
	board.call("clearSelection")
	board.call("removeTile", source)
	board.call("removeTile", sourceOther)
	board.call("removeTile", collisionCoordinates)
	assert((board.get("UndoStack") as Array).size() == historyBeforeMove)
