extends RefCounted

func run(context) -> void:
	await context.resetMain()
	await context.waitFrames(1)
	var main := context.MainSceneRoot as Control
	var board := context.CircuitBoard as Node2D
	var topBarContent := context.TopBarContent as Control
	var simulationModeButton := topBarContent.get_node("SimulationModeButton") as Button
	var previousTickButton := topBarContent.get_node("PreviousTickButton") as Button
	var loopStepButton := topBarContent.get_node("LoopStepButton") as Button
	var nextTickButton := topBarContent.get_node("NextTickButton") as Button
	var stepLengthControl := topBarContent.get_node("StepLengthControl") as Button
	var loopFrequencySlider := topBarContent.get_node("LoopFrequencySlider") as HSlider
	var simulationStatus := topBarContent.get_node("SimulationStatus") as Label
	var circuitEditorDock := context.getDockForSide(main, "left") as Control
	var orInkButton := (circuitEditorDock.get("InkButtons") as Dictionary).get("or") as Button
	var notCoordinates := Vector2i(-12, -12)
	var clockCoordinates := Vector2i(-10, -12)
	assert(board.call("placeTile", notCoordinates, "not"))
	assert(board.call("setTileState", notCoordinates, false))
	assert(board.call("placeTile", clockCoordinates, "clock"))
	assert(simulationModeButton.text == "Simulate")
	assert(previousTickButton.disabled)
	assert(loopStepButton.disabled)
	assert(nextTickButton.disabled)
	assert(stepLengthControl.disabled)
	assert(loopFrequencySlider.mouse_filter == Control.MOUSE_FILTER_IGNORE)
	assert(loopFrequencySlider.focus_mode == Control.FOCUS_NONE)
	assert(not simulationStatus.visible)
	main.call("enterSimulation")
	assert(bool(main.get("IsSimulating")))
	assert(bool(main.get("IsLooping")))
	assert((main.get("SimulationTimeline") as Array).is_empty())
	assert(not bool(board.get("EditorInputEnabled")))
	assert(not bool(board.call("getTileState", notCoordinates)))
	assert(bool(board.call("getRuntimeTileState", notCoordinates)))
	assert(bool(board.call("hasRuntimeTileState", notCoordinates)))
	assert(not bool(board.call("getRuntimeTileState", clockCoordinates)))
	assert(not orInkButton.disabled)
	assert(orInkButton.button_pressed)
	assert(orInkButton.mouse_filter == Control.MOUSE_FILTER_IGNORE)
	assert(orInkButton.focus_mode == Control.FOCUS_NONE)
	main.call("setClockHoldTicks", 9)
	assert(int(board.call("getClockHoldTicks")) == 1)
	assert(simulationModeButton.text == "Edit")
	assert(simulationStatus.visible)
	assertLoopStatus(simulationStatus)
	assert(stepLengthControl.disabled)
	assert(is_equal_approx(loopFrequencySlider.max_value, float(main.call("getLoopFrequencyMaximumTps"))))
	assert(loopFrequencySlider.value >= loopFrequencySlider.min_value)
	assert(loopFrequencySlider.value <= loopFrequencySlider.max_value)
	assert(loopFrequencySlider.mouse_filter == Control.MOUSE_FILTER_STOP)
	assert(loopFrequencySlider.focus_mode == Control.FOCUS_ALL)
	main.call("setLoopFrequency", 3.0)
	assertLoopStatus(simulationStatus)
	assert(float(main.get("LoopFrequency")) <= float(main.call("getLoopFrequencyMaximumTps")))
	assert(loopFrequencySlider.value >= loopFrequencySlider.min_value)
	assert(loopFrequencySlider.value <= loopFrequencySlider.max_value)
	main.call("toggleLoopStepMode")
	assert(not bool(main.get("IsLooping")))
	assert((main.get("SimulationTimeline") as Array).size() == 1)
	assert(simulationStatus.text == "Step Mode")
	assert(previousTickButton.disabled)
	assert(not nextTickButton.disabled)
	assert(not stepLengthControl.disabled)
	assert(loopFrequencySlider.mouse_filter == Control.MOUSE_FILTER_IGNORE)
	assert(loopFrequencySlider.focus_mode == Control.FOCUS_NONE)
	main.call("setSimulationStepLength", 3)
	assert(stepLengthControl.text == "3")
	main.call("showNextSimulationTick")
	assert(int(main.get("SimulationTick")) == 3)
	assert((main.get("SimulationTimeline") as Array).size() == 4)
	assert(bool(board.call("getRuntimeTileState", clockCoordinates)))
	assert(not previousTickButton.disabled)
	main.call("showPreviousSimulationTick")
	assert(int(main.get("SimulationTick")) == 0)
	assert(not bool(board.call("getRuntimeTileState", clockCoordinates)))
	main.call("toggleLoopStepMode")
	assert(bool(main.get("IsLooping")))
	var loopingAdvanceResult := main.call("advanceLoopingSimulation", 1, 1.0) as Dictionary
	assert(bool(loopingAdvanceResult.get("ok", false)))
	assert(int(loopingAdvanceResult.get("advancedTickCount", 0)) == 1)
	assert(bool(board.call("getRuntimeTileState", clockCoordinates)))
	main.call("leaveSimulation")
	assert(not bool(main.get("IsSimulating")))
	assert(bool(board.get("EditorInputEnabled")))
	assert(not bool(board.call("getTileState", notCoordinates)))
	assert(not bool(board.call("getRuntimeTileState", notCoordinates)))
	assert(not bool(board.call("hasRuntimeTileState", notCoordinates)))
	assert(not orInkButton.disabled)
	assert(orInkButton.mouse_filter == Control.MOUSE_FILTER_STOP)
	assert(orInkButton.focus_mode == Control.FOCUS_ALL)
	assert(simulationModeButton.text == "Simulate")
	assert(not simulationStatus.visible)
	assert(stepLengthControl.disabled)
	assert(loopFrequencySlider.mouse_filter == Control.MOUSE_FILTER_IGNORE)
	assert(loopFrequencySlider.focus_mode == Control.FOCUS_NONE)
	main.call("setSimulationStepLength", 1)
	assert(stepLengthControl.text == "1")
	assert(board.call("removeTile", notCoordinates))
	assert(board.call("removeTile", clockCoordinates))

func assertLoopStatus(status: Label) -> void:
	assert(not status.text.is_empty())
	assert(status.text.contains("TPS"))
